[theme]
primaryColor = "#00f2fe"
backgroundColor = "#030712"
secondaryBackgroundColor = "#0d132b"
textColor = "#f0f4fc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
